# version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      API_KEY: ${API_KEY}

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
